CREATE TABLE `document_upload_task` (
  `id` int NOT NULL AUTO_INCREMENT,
  `task_id` varchar(64) NOT NULL COMMENT '任务唯一标识',
  `user_id` int NOT NULL COMMENT '用户ID',
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `database_id` int NOT NULL COMMENT '知识库ID',
  `filename` varchar(255) NOT NULL COMMENT '文件名',
  `file_path` varchar(500) DEFAULT NULL COMMENT '文件路径',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小',
  `chunking_method` varchar(50) NOT NULL COMMENT '分块方式',
  `chunk_size` int DEFAULT '500' COMMENT '分块大小',
  `similarity_threshold` decimal(3,2) DEFAULT '0.70' COMMENT '相似度阈值',
  `overlap_size` int DEFAULT '100' COMMENT '重叠大小',
  `custom_delimiter` varchar(100) DEFAULT NULL COMMENT '自定义分隔符',
  `window_size` int DEFAULT '3' COMMENT '窗口大小',
  `step_size` int DEFAULT '1' COMMENT '步长',
  `min_chunk_size` int DEFAULT '50' COMMENT '最小分块大小',
  `max_chunk_size` int DEFAULT '2000' COMMENT '最大分块大小',
  `status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending' COMMENT '任务状态',
  `progress` int DEFAULT '0' COMMENT '处理进度(0-100)',
  `error_message` text COMMENT '错误信息',
  `chunk_count` int DEFAULT '0' COMMENT '生成的分块数量',
  `document_id` int DEFAULT NULL COMMENT '生成的文档ID',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `started_at` timestamp NULL DEFAULT NULL COMMENT '开始处理时间',
  `completed_at` timestamp NULL DEFAULT NULL COMMENT '完成时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_id` (`task_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_database_id` (`database_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文档上传任务表';