CREATE TABLE `embedding_model` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` varchar(100) NOT NULL COMMENT '模型显示名称',
  `model_type` varchar(50) NOT NULL COMMENT '模型类型：openai, zhipu, baidu, dashscope, xunfei, tencent, sentence_transformers, ollama',
  `api_type` varchar(20) NOT NULL COMMENT 'API类型：online, local',
  `api_key` varchar(500) DEFAULT NULL COMMENT 'API密钥（仅在线模型需要）',
  `api_url` varchar(500) DEFAULT NULL COMMENT 'API地址（预设，用户一般不需要修改）',
  `model_name` varchar(100) NOT NULL COMMENT '具体模型名称（如text-embedding-ada-002或BAAI/bge-large-zh-v1.5）',
  `local_path` varchar(500) DEFAULT NULL COMMENT '本地模型路径（可选，为空则自动下载到缓存）',
  `vector_dimension` int NOT NULL COMMENT '向量维度（由模型决定，不可修改）',
  `max_tokens` int NOT NULL COMMENT '最大token数（由模型决定，不可修改）',
  `batch_size` int DEFAULT '32' COMMENT '推荐批处理大小（可调整）',
  `timeout` int DEFAULT '30' COMMENT '请求超时时间（秒）',
  `is_default` tinyint(1) DEFAULT '0' COMMENT '是否为默认模型',
  `is_public` tinyint(1) DEFAULT '1' COMMENT '是否为公共模型（预设模型都是公共的）',
  `is_active` tinyint(1) DEFAULT '1' COMMENT '是否启用',
  `is_preset` tinyint(1) DEFAULT '0' COMMENT '是否为系统预设模型（预设模型不允许删除）',
  `user_id` int NOT NULL COMMENT '创建用户ID',
  `username` varchar(50) NOT NULL COMMENT '创建用户名',
  `description` text COMMENT '模型描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_name` (`name`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_model_type` (`model_type`),
  KEY `idx_api_type` (`api_type`),
  KEY `idx_is_default` (`is_default`),
  KEY `idx_is_preset` (`is_preset`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='嵌入模型配置表';